<#
================================================================================
  build_installer.ps1  —  PACKAGER.  Packs the compiled app folder into install.exe.

  Input  (produced by doc-qna\build.ps1 -- Nuitka compile + arrange):
    <DistDir>\
      yuktra-eq\            yuktra-eq.exe + runtime
      yuktra-eq-backend\    yuktra-eq-backend.exe + runtime
      data\   .env   MicrosoftEdgeWebView2RuntimeInstallerX64.exe   yuktra.png

  Output:
    <DistDir>\install.exe   (Inno Setup; install.exe sits IN the folder)

  install.exe on the target PC does the 8 tasks:
    1 WebView2 install (if missing)   2 choose install dir (default Program Files)
    3 yuktra-eq-backend.exe as auto-start background service + UI at startup
    4 register with Windows Defender (trusted)   5 firewall port whitelist
    6 desktop icon (yuktra-eq.exe)    7 require Windows restart   8 full uninstall

  Run:  .\build_installer.ps1                      (DistDir = doc-qna\emor)
        .\build_installer.ps1 -DistDir "<folder>"
================================================================================
#>
param(
    [string]$DistDir = "doc-qna\emor",  # compiled app folder (from doc-qna\build.ps1)
    [string]$Python,                    # optional python.exe (for png -> ico)
    [switch]$KeepWork                   # keep the temp Inno work folder
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
Set-Location $repo
if (-not [System.IO.Path]::IsPathRooted($DistDir)) { $DistDir = Join-Path $repo ($DistDir -replace '/', '\') }
if (-not (Test-Path $DistDir)) { throw "DistDir not found: $DistDir  (run doc-qna\build.ps1 first)" }
$DistDir = (Resolve-Path $DistDir).Path

$AppName     = 'Yuktra-YEQ'
$UiName      = 'yuktra-eq'
$BackendName = 'yuktra-eq-backend'
$WebView2Exe = 'MicrosoftEdgeWebView2RuntimeInstallerX64.exe'

$work    = Join-Path $env:TEMP 'yuktra-installer-build'
$issPath = Join-Path $work 'yuktra-eq.iss'
$icoPath = Join-Path $work 'yuktra.ico'
$nssmDst = Join-Path $work 'nssm.exe'

Write-Host "Packaging folder : $DistDir" -ForegroundColor Cyan

# --- verify the compiled payload ---
$required = @("$DistDir\$UiName\$UiName.exe", "$DistDir\$BackendName\$BackendName.exe", "$DistDir\$WebView2Exe")
$missing = $required | Where-Object { -not (Test-Path $_) }
if ($missing) { throw "Missing payload (run doc-qna\build.ps1 first):`n  " + ($missing -join "`n  ") }
Write-Host "Payload OK." -ForegroundColor Green

if (Test-Path $work) { Remove-Item $work -Recurse -Force }
New-Item -ItemType Directory -Force -Path $work | Out-Null

# --- icon: yuktra.png -> yuktra.ico (Pillow), else cached repo ico ---
$py = if ($Python) { $Python } elseif (Test-Path "$repo\venv\Scripts\python.exe") { "$repo\venv\Scripts\python.exe" } else { 'python' }
$png = Join-Path $DistDir 'yuktra.png'
if (Test-Path $png) {
    try { & $py -c "from PIL import Image; Image.open(r'$png').convert('RGBA').save(r'$icoPath', sizes=[(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)])" 2>$null } catch {}
}
if (-not (Test-Path $icoPath)) {
    $icoSrc = @("$repo\installer\icons\yuktra.ico") | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($icoSrc) { Copy-Item $icoSrc $icoPath -Force }
}
$haveIcon = Test-Path $icoPath

# --- nssm (service tool) ---
$nssmSrc = @("$repo\pre-requisite-icon\nssm-2.24\nssm-2.24\win64\nssm.exe", "$repo\installer\tools\nssm.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $nssmSrc) { throw "nssm.exe not found (pre-requisite-icon\nssm-2.24\...\win64 or installer\tools)." }
Copy-Item $nssmSrc $nssmDst -Force

$setupIconLine = if ($haveIcon) { "SetupIconFile=$icoPath" } else { '' }
$iconFileFlag  = if ($haveIcon) { "; IconFilename: ""{app}\yuktra.ico""" } else { '' }
$iconSourceLn  = if ($haveIcon) { "Source: ""$icoPath""; DestDir: ""{app}""; DestName: ""yuktra.ico""; Flags: ignoreversion" } else { '' }

$iss = @"
; AUTO-GENERATED by build_installer.ps1
#define AppName       "$AppName"
#define AppVersion    "1.0.0"
#define AppPublisher  "Emorphis"
#define SvcName       "YuktraEQBackend"
#define BackendDir    "$BackendName"
#define BackendExe    "$BackendName.exe"
#define UiDir         "$UiName"
#define LauncherExe   "$UiName.exe"
#define WebView2Exe   "$WebView2Exe"

[Setup]
AppId={{8E5C1A10-YUKT-RAEQ-0001-PRODUCTGUID00}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=no
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64
OutputDir=$DistDir
OutputBaseFilename=install
Compression=lzma2/normal
SolidCompression=yes
WizardStyle=modern
$setupIconLine
UninstallDisplayIcon={app}\{#UiDir}\{#LauncherExe}
AlwaysRestart=yes

[Tasks]
Name: "autostartui"; Description: "Launch {#AppName} automatically when Windows starts"; GroupDescription: "Startup options:"

[Files]
; The app (exes), .env, png, WebView2 and data are ALL already in the folder next
; to install.exe -> use them EXTERNAL (copied at install time, NOT compiled into
; install.exe). Only nssm + icon are bundled. This keeps install.exe tiny and the
; Inno compile + zip fast (no duplicate of the multi-GB app inside install.exe).
Source: "{src}\$UiName\*";       DestDir: "{app}\{#UiDir}";      Flags: external recursesubdirs createallsubdirs ignoreversion
Source: "{src}\$BackendName\*";  DestDir: "{app}\{#BackendDir}"; Flags: external recursesubdirs createallsubdirs ignoreversion
Source: "{src}\.env";            DestDir: "{app}"; Flags: external ignoreversion skipifsourcedoesntexist
Source: "{src}\yuktra.png";      DestDir: "{app}"; Flags: external ignoreversion skipifsourcedoesntexist
$iconSourceLn
Source: "$nssmDst";              DestDir: "{app}"; Flags: ignoreversion
; data\ -> {app}\data, but NOT bundled into install.exe (that 2.9 GB is already
; in the folder next to install.exe). external = copied at install time from
; {src}\data (the folder install.exe runs from). Keeps install.exe small + fast.
Source: "{src}\data\*"; DestDir: "{app}\data"; Flags: external recursesubdirs createallsubdirs skipifsourcedoesntexist
Source: "{src}\{#WebView2Exe}"; DestDir: "{tmp}"; Flags: external deleteafterinstall

[Dirs]
Name: "{app}\data"; Permissions: users-modify
Name: "{app}\data\logs"; Permissions: users-modify

[Icons]
Name: "{autodesktop}\{#AppName}";     Filename: "{app}\{#UiDir}\{#LauncherExe}"; WorkingDir: "{app}\{#UiDir}"$iconFileFlag
Name: "{group}\{#AppName}";           Filename: "{app}\{#UiDir}\{#LauncherExe}"; WorkingDir: "{app}\{#UiDir}"$iconFileFlag
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "DATA_DIR";            ValueData: "{app}\data"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_QNA_API_HOST"; ValueData: "127.0.0.1"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_QNA_API_PORT"; ValueData: "{code:GetBackendPort}"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_QNA_API_BASE"; ValueData: "http://127.0.0.1:{code:GetBackendPort}"; Flags: preservestringtype uninsdeletevalue
; TTS (piper) + STT (faster-whisper) run via the bundled portable Python under
; {app}\{#UiDir}\python (it has piper-tts + faster-whisper from the venv). These
; env vars point the backend at it + the Windows model paths (overriding the
; stale Linux paths in .env). System env -> the service inherits them after the
; post-install restart.
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_PIPER_PYTHON";      ValueData: "{app}\{#UiDir}\python\python.exe"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_PIPER_MODEL_PATH";  ValueData: "{app}\data\models\piper\en_IN-medium.onnx"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_STT_PYTHON";        ValueData: "{app}\{#UiDir}\python\python.exe"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_FASTER_WHISPER_DIR"; ValueData: "{app}\data\models\faster-whisper-tiny"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_WHISPER_MODEL_PATH"; ValueData: "{app}\data\models\ggml-base.bin"; Flags: preservestringtype uninsdeletevalue
; LLM/embeddings: runtime auto-detects GPU (Vulkan) via llama_supports_gpu_offload() and
; falls back to CPU. Optional override: YUKTRA_LLM_N_GPU_LAYERS=0 to force CPU.
; STT: auto picks CUDA on NVIDIA, else CPU.
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "YUKTRA_WHISPER_DEVICE"; ValueData: "auto"; Flags: preservestringtype uninsdeletevalue
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "{#AppName}"; ValueData: """{app}\{#UiDir}\{#LauncherExe}"""; Flags: uninsdeletevalue; Tasks: autostartui
Root: HKLM; Subkey: "Software\{#AppPublisher}\{#AppName}"; ValueType: string; ValueName: "DataDir";     ValueData: "{app}\data"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\{#AppPublisher}\{#AppName}"; ValueType: string; ValueName: "BackendPort"; ValueData: "{code:GetBackendPort}"
Root: HKLM; Subkey: "Software\{#AppPublisher}\{#AppName}"; ValueType: string; ValueName: "UiPort";      ValueData: "{code:GetUiPort}"

[Code]
var
  PortPage: TInputQueryWizardPage;
function GetBackendPort(Param: string): string;
begin
  if Assigned(PortPage) and (Trim(PortPage.Values[0]) <> '') then Result := Trim(PortPage.Values[0]) else Result := '8008';
end;
function GetUiPort(Param: string): string;
begin
  if Assigned(PortPage) and (Trim(PortPage.Values[1]) <> '') then Result := Trim(PortPage.Values[1]) else Result := '8009';
end;
procedure InitializeWizard;
begin
  PortPage := CreateInputQueryPage(wpSelectDir, 'Network ports', 'Choose the ports Yuktra-YEQ will use', 'Backend API and UI ports (defaults are fine for most setups).');
  PortPage.Add('Backend port:', False); PortPage.Add('UI port:', False);
  PortPage.Values[0] := '8008'; PortPage.Values[1] := '8009';
end;
function WebView2Installed(): Boolean;
var v: string;
begin
  Result := RegQueryStringValue(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDB-FCBA1C7C9C2B}', 'pv', v) or
            RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDB-FCBA1C7C9C2B}', 'pv', v);
end;
procedure RunHidden(const Exe, Params: string);
var rc: Integer;
begin
  Exec(Exe, Params, '', SW_HIDE, ewWaitUntilTerminated, rc);
end;
{ Live progress text during the post-install steps (else they look frozen). }
procedure Status(const S: string);
begin
  if Assigned(WizardForm) then begin
    WizardForm.StatusLabel.Caption := S;
    WizardForm.StatusLabel.Update;
    WizardForm.Refresh;
  end;
end;
procedure CurStepChanged(CurStep: TSetupStep);
var app, data, backend, launcher, runner, nssm, bp, up, ps: string;
begin
  if CurStep = ssPostInstall then
  begin
    app := ExpandConstant('{app}'); data := app + '\data';
    backend := app + '\{#BackendDir}\{#BackendExe}'; launcher := app + '\{#UiDir}\{#LauncherExe}';
    runner := app + '\{#UiDir}\webview-runner.exe'; nssm := app + '\nssm.exe';
    bp := GetBackendPort(''); up := GetUiPort('');
    WizardForm.ProgressGauge.Style := npbstMarquee;
    Status('Installing the WebView2 runtime (this can take a few minutes)...');
    if not WebView2Installed() then RunHidden(ExpandConstant('{tmp}\{#WebView2Exe}'), '/silent /install');
    Status('Registering the app as trusted (Windows Defender)...');
    { Defender trusted: backend + frontend exes + launcher + portable python + folders.
      ExclusionPath covers files stored there; ExclusionProcess stops real-time scanning
      of running processes (critical: pythonw.exe importing streamlit triggers AV kills). }
    ps := 'Add-MpPreference -ExclusionPath ''' + app + ''' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionPath ''' + data + ''' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionProcess ''' + backend + ''' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionProcess ''' + runner + ''' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionProcess ''' + launcher + ''' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionProcess ''' + app + '\{#UiDir}\python\python.exe'' -EA SilentlyContinue; ' +
          'Add-MpPreference -ExclusionProcess ''' + app + '\{#UiDir}\python\pythonw.exe'' -EA SilentlyContinue';
    RunHidden('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -Command "' + ps + '"');
    Status('Creating the background service...');
    RunHidden(nssm, 'install {#SvcName} "' + backend + '"');
    RunHidden(nssm, 'set {#SvcName} AppDirectory "' + app + '\{#BackendDir}"');
    RunHidden(nssm, 'set {#SvcName} Start SERVICE_AUTO_START');
    RunHidden(nssm, 'set {#SvcName} AppStdout "' + data + '\logs\service.log"');
    RunHidden(nssm, 'set {#SvcName} AppStderr "' + data + '\logs\service.log"');
    { Each KEY=VALUE is double-quoted so paths with spaces (e.g. Program Files) are
      passed as one argument to NSSM, not split at the space character. }
    RunHidden(nssm, 'set {#SvcName} AppEnvironmentExtra "DATA_DIR=' + data + '" "YUKTRA_QNA_API_HOST=127.0.0.1" "YUKTRA_QNA_API_PORT=' + bp + '" "YUKTRA_QNA_API_BASE=http://127.0.0.1:' + bp + '" "YUKTRA_QNA_SKIP_WARMUP=1"');
    RunHidden(nssm, 'start {#SvcName}');
    Status('Configuring Windows Firewall...');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Backend In" dir=in action=allow program="' + backend + '" enable=yes');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Backend Out" dir=out action=allow program="' + backend + '" enable=yes');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Port ' + bp + ' In" dir=in action=allow protocol=TCP localport=' + bp + ' enable=yes');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Port ' + up + ' In" dir=in action=allow protocol=TCP localport=' + up + ' enable=yes');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Port ' + bp + ' Out" dir=out action=allow protocol=TCP localport=' + bp + ' enable=yes');
    RunHidden(ExpandConstant('{sys}\netsh.exe'), 'advfirewall firewall add rule name="YuktraEQ Port ' + up + ' Out" dir=out action=allow protocol=TCP localport=' + up + ' enable=yes');
    Status('Finishing setup...');
    WizardForm.ProgressGauge.Style := npbstNormal;
  end;
end;
function GetStoredPort(ValueName, Default: string): string;
var v: string;
begin
  if RegQueryStringValue(HKLM, 'Software\{#AppPublisher}\{#AppName}', ValueName, v) and (Trim(v) <> '') then Result := Trim(v) else Result := Default;
end;
function InitializeUninstall(): Boolean;
begin
  Result := MsgBox('This will COMPLETELY remove {#AppName} and ALL of its data'#13#10 + '(documents, models, vector store, chat history and logs).'#13#10#13#10 + 'Continue?', mbConfirmation, MB_YESNO) = IDYES;
end;
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var app, data, backend, launcher, runner, nssm, sys, bp, up: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    app := ExpandConstant('{app}'); backend := app + '\{#BackendDir}\{#BackendExe}'; launcher := app + '\{#UiDir}\{#LauncherExe}';
    runner := app + '\{#UiDir}\webview-runner.exe'; nssm := app + '\nssm.exe'; sys := ExpandConstant('{sys}\netsh.exe');
    bp := GetStoredPort('BackendPort', '8008'); up := GetStoredPort('UiPort', '8009');
    RunHidden(nssm, 'stop {#SvcName}'); RunHidden(nssm, 'remove {#SvcName} confirm');
    RunHidden(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#BackendExe}');
    RunHidden(ExpandConstant('{sys}\taskkill.exe'), '/F /IM webview-runner.exe');
    RunHidden(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#LauncherExe}');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Backend In"');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Backend Out"');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Port ' + bp + ' In"');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Port ' + up + ' In"');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Port ' + bp + ' Out"');
    RunHidden(sys, 'advfirewall firewall delete rule name="YuktraEQ Port ' + up + ' Out"');
    RunHidden('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -Command "' +
      'Remove-MpPreference -ExclusionPath ''' + app + ''' -EA SilentlyContinue; ' +
      'Remove-MpPreference -ExclusionProcess ''' + backend + ''' -EA SilentlyContinue; ' +
      'Remove-MpPreference -ExclusionProcess ''' + runner + ''' -EA SilentlyContinue; ' +
      'Remove-MpPreference -ExclusionProcess ''' + launcher + ''' -EA SilentlyContinue"');
    { data lives in app\data -> removed with the app folder in usPostUninstall. }
    DelTree(app + '\data', True, True, True);
  end
  else if CurUninstallStep = usPostUninstall then
    DelTree(ExpandConstant('{app}'), True, True, True);
end;
"@

Set-Content -Path $issPath -Value $iss -Encoding ASCII

$iscc = @("${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe", "$env:ProgramFiles\Inno Setup 6\ISCC.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $iscc) {
    $innoExe = Get-ChildItem "$repo\pre-requisite-icon" -Filter 'innosetup*.exe' -EA SilentlyContinue | Select-Object -First 1
    if ($innoExe) {
        Start-Process $innoExe.FullName -ArgumentList '/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/SP-' -Wait
        $iscc = @("${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe","$env:ProgramFiles\Inno Setup 6\ISCC.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
    }
}
if (-not $iscc) { throw "Inno Setup (ISCC.exe) not found." }

Write-Host "Compiling install.exe ..." -ForegroundColor Cyan
$log = Join-Path $work 'iscc.log'
$proc = Start-Process -FilePath $iscc -ArgumentList @($issPath) -WorkingDirectory $work -NoNewWindow -Wait -PassThru -RedirectStandardOutput $log -RedirectStandardError "$log.err"
if ($proc.ExitCode -ne 0) { if (Test-Path "$log.err") { Get-Content "$log.err" }; throw "Inno Setup compile failed ($($proc.ExitCode))." }
if (-not (Test-Path "$DistDir\install.exe")) { throw "install.exe was not produced." }
if (-not $KeepWork) { Remove-Item $work -Recurse -Force -EA SilentlyContinue }

$gb = [math]::Round((Get-Item "$DistDir\install.exe").Length / 1GB, 2)
Write-Host "`n=== DONE ===" -ForegroundColor Green
Write-Host "Installer : $DistDir\install.exe   ($gb GB)"
Write-Host "Folder    : data\, $UiName\, $BackendName\, .env, $WebView2Exe, yuktra.png, install.exe"
